
services:
  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=redispassword
    command: ["redis-server", "--requirepass", "redispassword"]

